module org.apache.commons.math4 {
	exports org.apache.commons.math4;

	/*requires static commons.numbers.core;
	requires static commons.numbers.arrays;
	requires static commons.numbers.combinatorics;*/
	requires static org.apache.commons.rng.sampling;
	/*requires static commons.numbers.complex;
	requires static commons.numbers.complex.streams;*/
	requires static org.apache.commons.rng.api;
	//requires static commons.statistics.distribution;
	requires static org.apache.commons.rng.simple;
	//requires static commons.numbers.angle;
	requires static org.apache.commons.rng.core;
	//requires static commons.numbers.gamma;

	exports org.apache.commons.math4.analysis;
	exports org.apache.commons.math4.complex;
	exports org.apache.commons.math4.dfp;
	exports org.apache.commons.math4.distribution;
	exports org.apache.commons.math4.distribution.fitting;
	//exports org.apache.commons.math4.exception;
	//exports org.apache.commons.math4.exception.util;
	exports org.apache.commons.math4.filter;
	exports org.apache.commons.math4.fitting;
	exports org.apache.commons.math4.fitting.leastsquares;
	exports org.apache.commons.math4.fraction;
	exports org.apache.commons.math4.genetics;
	exports org.apache.commons.math4.geometry;
	exports org.apache.commons.math4.geometry.enclosing;
	exports org.apache.commons.math4.geometry.euclidean.oned;
	exports org.apache.commons.math4.geometry.euclidean.twod;
	exports org.apache.commons.math4.geometry.euclidean.threed;
	exports org.apache.commons.math4.geometry.hull;
	exports org.apache.commons.math4.geometry.partitioning;
	exports org.apache.commons.math4.geometry.spherical.oned;
	exports org.apache.commons.math4.geometry.spherical.twod;
	exports org.apache.commons.math4.linear;
	exports org.apache.commons.math4.ml.clustering;
	exports org.apache.commons.math4.ml.clustering.evaluation;
	exports org.apache.commons.math4.ml.distance;
	exports org.apache.commons.math4.ml.neuralnet;
	exports org.apache.commons.math4.ml.neuralnet.oned;
	exports org.apache.commons.math4.ml.neuralnet.twod;
	exports org.apache.commons.math4.ml.neuralnet.twod.util;
	exports org.apache.commons.math4.ml.neuralnet.sofm;
	exports org.apache.commons.math4.ml.neuralnet.sofm.util;
	exports org.apache.commons.math4.ode;
	exports org.apache.commons.math4.ode.events;
	exports org.apache.commons.math4.ode.nonstiff;
	exports org.apache.commons.math4.ode.sampling;
	exports org.apache.commons.math4.optim;
	exports org.apache.commons.math4.optim.linear;
	exports org.apache.commons.math4.optim.nonlinear.scalar;
	exports org.apache.commons.math4.optim.nonlinear.scalar.gradient;
	exports org.apache.commons.math4.optim.nonlinear.scalar.noderiv;
	//exports org.apache.commons.math4.random;
	exports org.apache.commons.math4.special;
	exports org.apache.commons.math4.stat;
	exports org.apache.commons.math4.stat.correlation;
	exports org.apache.commons.math4.stat.descriptive;
	exports org.apache.commons.math4.stat.descriptive.moment;
	exports org.apache.commons.math4.stat.descriptive.rank;
	exports org.apache.commons.math4.stat.descriptive.summary;
	exports org.apache.commons.math4.stat.inference;
	exports org.apache.commons.math4.stat.interval;
	exports org.apache.commons.math4.stat.ranking;
	exports org.apache.commons.math4.stat.regression;
	exports org.apache.commons.math4.transform;
	exports org.apache.commons.math4.util;
}